#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

# Updates the package lists for available software packages.
sudo apt-get update
# Installs the Nginx web server.
sudo apt-get install -y nginx

# Creates the /etc/nginx/html directory, which will serve as the document root directory for Nginx.
sudo mkdir /etc/nginx/html
# Creates an empty index.html file inside the /etc/nginx/html directory.
sudo touch /etc/nginx/html/index.html
# Sets the content of the index.html file to "Hello World!" using the echo command.
echo "Hello World!" | sudo tee /etc/nginx/html/index.html > /dev/null
# Sets Nginx to listen on port 80 and serve files from the /etc/nginx/html directory.
printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" | sudo tee /etc/nginx/sites-available/default > /dev/null

# Restarts the Nginx service to apply the configuration changes.
sudo service nginx restart
