#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me redirects to another page.
# The redirection is configured as a "301 Moved Permanently"
# Includes a custom 404 page containing "Ceci n'est pas une page".

#  updates the package lists for available software packages.
apt-get update
# installs the Nginx web server.
apt-get install -y nginx

# Creates the /etc/nginx/html directory, which will serve as the document root directory for Nginx.
mkdir /etc/nginx/html
#  creates an empty index.html file inside the /etc/nginx/html directory.
touch /etc/nginx/html/index.html
#  sets the content of the index.html file to "Hello World!" using the echo command.
echo "Hello World!" > /etc/nginx/html/index.html
# Sets Nginx to listen on port 80 and serve files from the /etc/nginx/html directory.
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
