#!/usr/bin/env bash

#Configures an Nginx server to listen to port 80

# rm the default Nginx configuration file
rm /etc/nginx/sites-enabled/default

# Configures Nginx to listen on port 80 for all active IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
